#%RAML 1.0
securitySchemes:
  basicAuth: !include ./securitySchemes/basicAuth.raml
title: Example API illustrating RAML best practices
version: v1
baseUri: http://api.example.com/{version}

mediaType: application/json
protocols: HTTPS
securedBy: basicAuth
documentation:
  - !include documentation/customer.doc.raml
  
uses:
  resType: resourceTypes/resourceTypes.lib.raml
  cusType: schemas/customerTypes.raml
  tr: traits/traits.lib.raml

/customers:
  type:
    {
      resType.collection: {
        getResponseType: cusType.GetCustomersResponse,
        postRequestType: cusType.PostCustomerRequest,
        getResponseExample: !include examples/getCustomersResponse.json,
        postRequestExample: !include examples/postCustomerRequest.json
      }
    }
  get:
    is: [ tr.pageable, tr.searchable, tr.sortable, tr.syncable, tr.expandable ]
  post:
  /{customerId}:
    type:
      {
        resType.member: {
          getResponseType: cusType.GetCustomerResponse,
          putRequestType : cusType.PutCustomerRequest,
          getResponseExample: !include examples/getCustomerResponse.json,
          putRequestExample: !include examples/putCustomerRequest.json,
          patchRequestExample: !include examples/patchCustomerRequest.raml
        }
      }
    get:
      is: [tr.cacheable, tr.expandable]
    put:
    patch:
    delete:
    /addresses:
      type:
        {
          resType.collection: {
            getResponseType: cusType.GetAddressesResponse,
            postRequestType: cusType.PostAddressRequest,
            getResponseExample: !include examples/getAddressesResponse.json,
            postRequestExample: !include examples/postAddressRequest.json
          }
        }
      get:
        is: [ tr.sortable ]
      post:
        description: Adds a new address to the customer
      /{addressId}:
        type:
          {
            resType.member: {
              getResponseType: cusType.GetAddressResponse,
              putRequestType : cusType.PutAddressRequest,
              getResponseExample: !include examples/getAddressResponse.json,
              putRequestExample: !include examples/putAddressRequest.json,
              patchRequestExample: !include examples/patchAddressRequest.raml
            }
          }
        get:
          is: [ tr.cacheable ]
        put:
        patch:
        delete:
