#%RAML 1.0
securitySchemes:
  basicAuth: !include ./securitySchemes/basicAuth.raml
title: Example API illustrating RAML best practices
version: v1
baseUri: http://api.example.com/{version}

mediaType: application/vnd.api+json
protocols: HTTPS
securedBy: basicAuth
documentation:
  - !include documentation/customer.doc.raml
  
uses:
  api: libraries/jsonApiLibrary.raml
  col: libraries/jsonApiCollections.raml
  cus: libraries/customerTypes.raml
  tr: libraries/customTraits.raml

/customers:
  type:
    col.collection:
      dataType: cus.customer
      exampleCollection: !include examples/CustomerCollection.json
      exampleItem: !include examples/CustomerItem.json
  get:
    is: [ col.pageable, col.filterable, col.sortable, tr.syncable, col.includable ]
  post:

  /{customerId}:
    type:
      col.item:
        dataType: cus.customer
        exampleItem: !include examples/CustomerItem.json
    get:
      is: [col.sparse, col.includable]
    put:
    patch:
    delete:

    /addresses:
      type:
        col.collection:
          dataType: cus.address
          exampleCollection: !include examples/AddressCollection.json
          exampleItem: !include examples/AddressItem.json
      get:
        is: [ col.sortable ]
      post:
        description: Adds a new address to the customer
      /{addressId}:
        type:
          col.item:
            dataType: cus.address
            exampleItem: !include examples/AddressItem.json
        get:
          is: [ tr.cacheable ]
        put:
        patch:
        delete:
