#%RAML 1.0 Trait
usage: |
  Apply this trait to a collection GET method that supports paging over a
  collection of resources
queryParameters:
  pageIndex:
    description: The index of the page to retrieve
    type: integer
    default: 1
    example: 1
    required: false
  pageSize:
    description: The number of items per page, capped at 1000.
    type: integer
    default: 10
    example: 10
    required: false
