#%RAML 1.0 Trait
usage: |
  Apply this trait to a collection GET method that supports searching
  a collection of resources

queryParameters:
  q:
    description: |
      A search query consisting of a comma-separated list of (field=value)
      terms. Values can contain asterisks for partial matching.

    required: false
    example: firstName='John',lastName='Sm*',phone="0499009123"
