#%RAML 1.0 Library

traits:
  cacheable: !include cacheable.raml
  pageable: !include pageable.raml
  searchable: !include searchable.raml
  sortable: !include sortable.raml
  syncable: !include syncable.raml
  expandable: !include expandable.raml
